_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 26412b78-f8da-4588-84cb-914235d18cd7
name: Tugboat
mail: support@tugboatqa.com
slogan: 'Deploy with Confidence'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
