_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 12e38ccc-19ee-4dce-935a-037ca821f98a
name: 'My Cool Tugboat Demo'
mail: support@tugboatqa.com
slogan: 'Goats in tubs!'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
